export const ROUTES = {
  HOME: '/',
  LOGIN: '/auth/login',
  DASHBOARD: '/dashboard',
  PATIENTS: '/dashboard/patients',
  AI_ASSISTANT: '/dashboard/ai-assistant',
  VOICE_NOTES: '/dashboard/voice-notes',
  DOCUMENTS: '/dashboard/documents',
  PATIENT_REPORT: '/dashboard/patient-report',
  VIDEO_CALL: '/video-call',
  PATIENT_PORTAL: '/patient-portal',
  SECURITY: '/security',
  BLOCKCHAIN: '/blockchain',
  SETTINGS: '/settings',
} as const;